name: Graphics CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  ui-regressions:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VFLAGS: -cc tcc
      DISPLAY: :99
      LIBGL_ALWAYS_SOFTWARE: 1
      VUI_FONT: /usr/share/fonts/truetype/inconsolata/Inconsolata.otf
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout V UI
        uses: actions/checkout@v2
        with:
          path: vlib/ui

      - name: Build V
        run: make

      - name: Setup dependencies
        run: |
          # xvfb                     : xvfb
          # openimageio-tools        : idiff
          # libxcursor-dev libxi-dev : V gfx deps
          # mesa-common-dev, mesa-utils : For headless rendering
          # freeglut3-dev            : Fixes graphic apps compilation with tcc
          # fonts-inconsolata        : A fixed font, instead of relying on the system font selection.
          sudo apt-get install xvfb imagemagick openimageio-tools mesa-common-dev mesa-utils libxcursor-dev libxi-dev freeglut3-dev fonts-inconsolata
          wget https://raw.githubusercontent.com/tremby/imgur.sh/c98345d/imgur.sh
          chmod +x ./imgur.sh
          git clone https://github.com/Larpon/ui-regression-images ui-regression-images

      - name: Show ui-regression-images and ui versions
        run: |
          ls -lart $VUI_FONT
          echo "ui-regression-images commit: $(git -C ui-regression-images/ rev-list HEAD -n1)"
          echo "vlib/ui commit: $(git -C vlib/ui/ rev-list HEAD -n1)"

      - name: Sample and compare
        id: compare
        continue-on-error: true
        run: |
          Xvfb $DISPLAY -screen 0 1280x1024x24 &
          ./v gret -r vlib/ui -t ./ui-regression-images/vgret.ui_examples.toml -v ./ui-sample_images ./ui-regression-images

      - name: Upload regression to imgur
        if: steps.compare.outcome != 'success'
        run: |
          ./imgur.sh /tmp/fail.png
          exit 1
